app_public:
    resource: "@AppPublicBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:     /suit-up
    defaults: { _controller: AppPublicBundle:UnAuth:auth }

login_check:
    path: /login_check

logout:
    path: /logout

